cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_dddd_MS55_ctauS1.root outputFile=file:/tmp/almorton/step1_HZJ_dddd_MS55_ctauS1.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_dddd_MS55_ctauS10.root outputFile=file:/tmp/almorton/step1_HZJ_dddd_MS55_ctauS10.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_dddd_MS55_ctauS100.root outputFile=file:/tmp/almorton/step1_HZJ_dddd_MS55_ctauS100.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_dddd_MS55_ctauS1000.root outputFile=file:/tmp/almorton/step1_HZJ_dddd_MS55_ctauS1000.root

cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_dddd_MS40_ctauS1.root outputFile=file:/tmp/almorton/step1_HZJ_dddd_MS40_ctauS1.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_dddd_MS40_ctauS10.root outputFile=file:/tmp/almorton/step1_HZJ_dddd_MS40_ctauS10.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_dddd_MS40_ctauS100.root outputFile=file:/tmp/almorton/step1_HZJ_dddd_MS40_ctauS100.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_dddd_MS40_ctauS1000.root outputFile=file:/tmp/almorton/step1_HZJ_dddd_MS40_ctauS1000.root

cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_dddd_MS2_ctauS1.root outputFile=file:/tmp/almorton/step1_HZJ_dddd_MS2_ctauS1.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_dddd_MS2_ctauS10.root outputFile=file:/tmp/almorton/step1_HZJ_dddd_MS2_ctauS10.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_dddd_MS2_ctauS100.root outputFile=file:/tmp/almorton/step1_HZJ_dddd_MS2_ctauS100.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_dddd_MS2_ctauS1000.root outputFile=file:/tmp/almorton/step1_HZJ_dddd_MS2_ctauS1000.root

cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_dddd_MS1_ctauS1.root outputFile=file:/tmp/almorton/step1_HZJ_dddd_MS1_ctauS1.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_dddd_MS1_ctauS10.root outputFile=file:/tmp/almorton/step1_HZJ_dddd_MS1_ctauS10.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_dddd_MS1_ctauS100.root outputFile=file:/tmp/almorton/step1_HZJ_dddd_MS1_ctauS100.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_dddd_MS1_ctauS1000.root outputFile=file:/tmp/almorton/step1_HZJ_dddd_MS1_ctauS1000.root

###

cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_dddd_MS55_ctauS1.root outputFile=file:/tmp/almorton/step1_HZJ_dddd_MS55_ctauS1.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_dddd_MS55_ctauS10.root outputFile=file:/tmp/almorton/step1_HZJ_dddd_MS55_ctauS10.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_dddd_MS55_ctauS100.root outputFile=file:/tmp/almorton/step1_HZJ_dddd_MS55_ctauS100.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_dddd_MS55_ctauS1000.root outputFile=file:/tmp/almorton/step1_HZJ_dddd_MS55_ctauS1000.root

cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_dddd_MS40_ctauS1.root outputFile=file:/tmp/almorton/step1_HZJ_dddd_MS40_ctauS1.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_dddd_MS40_ctauS10.root outputFile=file:/tmp/almorton/step1_HZJ_dddd_MS40_ctauS10.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_dddd_MS40_ctauS100.root outputFile=file:/tmp/almorton/step1_HZJ_dddd_MS40_ctauS100.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_dddd_MS40_ctauS1000.root outputFile=file:/tmp/almorton/step1_HZJ_dddd_MS40_ctauS1000.root

cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_dddd_MS2_ctauS1.root outputFile=file:/tmp/almorton/step1_HZJ_dddd_MS2_ctauS1.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_dddd_MS2_ctauS10.root outputFile=file:/tmp/almorton/step1_HZJ_dddd_MS2_ctauS10.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_dddd_MS2_ctauS100.root outputFile=file:/tmp/almorton/step1_HZJ_dddd_MS2_ctauS100.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_dddd_MS2_ctauS1000.root outputFile=file:/tmp/almorton/step1_HZJ_dddd_MS2_ctauS1000.root

cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_dddd_MS1_ctauS1.root outputFile=file:/tmp/almorton/step1_HZJ_dddd_MS1_ctauS1.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_dddd_MS1_ctauS10.root outputFile=file:/tmp/almorton/step1_HZJ_dddd_MS1_ctauS10.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_dddd_MS1_ctauS100.root outputFile=file:/tmp/almorton/step1_HZJ_dddd_MS1_ctauS100.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_dddd_MS1_ctauS1000.root outputFile=file:/tmp/almorton/step1_HZJ_dddd_MS1_ctauS1000.root

###

cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_ssss_MS55_ctauS1.root outputFile=file:/tmp/almorton/step1_HZJ_ssss_MS55_ctauS1.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_ssss_MS55_ctauS10.root outputFile=file:/tmp/almorton/step1_HZJ_ssss_MS55_ctauS10.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_ssss_MS55_ctauS100.root outputFile=file:/tmp/almorton/step1_HZJ_ssss_MS55_ctauS100.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_ssss_MS55_ctauS1000.root outputFile=file:/tmp/almorton/step1_HZJ_ssss_MS55_ctauS1000.root

cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_ssss_MS40_ctauS1.root outputFile=file:/tmp/almorton/step1_HZJ_ssss_MS40_ctauS1.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_ssss_MS40_ctauS10.root outputFile=file:/tmp/almorton/step1_HZJ_ssss_MS40_ctauS10.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_ssss_MS40_ctauS100.root outputFile=file:/tmp/almorton/step1_HZJ_ssss_MS40_ctauS100.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_ssss_MS40_ctauS1000.root outputFile=file:/tmp/almorton/step1_HZJ_ssss_MS40_ctauS1000.root

cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_ssss_MS2_ctauS1.root outputFile=file:/tmp/almorton/step1_HZJ_ssss_MS2_ctauS1.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_ssss_MS2_ctauS10.root outputFile=file:/tmp/almorton/step1_HZJ_ssss_MS2_ctauS10.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_ssss_MS2_ctauS100.root outputFile=file:/tmp/almorton/step1_HZJ_ssss_MS2_ctauS100.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_ssss_MS2_ctauS1000.root outputFile=file:/tmp/almorton/step1_HZJ_ssss_MS2_ctauS1000.root

###

cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_cccc_MS55_ctauS1.root outputFile=file:/tmp/almorton/step1_HZJ_cccc_MS55_ctauS1.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_cccc_MS55_ctauS10.root outputFile=file:/tmp/almorton/step1_HZJ_cccc_MS55_ctauS10.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_cccc_MS55_ctauS100.root outputFile=file:/tmp/almorton/step1_HZJ_cccc_MS55_ctauS100.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_cccc_MS55_ctauS1000.root outputFile=file:/tmp/almorton/step1_HZJ_cccc_MS55_ctauS1000.root

cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_cccc_MS40_ctauS1.root outputFile=file:/tmp/almorton/step1_HZJ_cccc_MS40_ctauS1.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_cccc_MS40_ctauS10.root outputFile=file:/tmp/almorton/step1_HZJ_cccc_MS40_ctauS10.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_cccc_MS40_ctauS100.root outputFile=file:/tmp/almorton/step1_HZJ_cccc_MS40_ctauS100.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_cccc_MS40_ctauS1000.root outputFile=file:/tmp/almorton/step1_HZJ_cccc_MS40_ctauS1000.root

Â£Â###

cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_bbbb_MS55_ctauS1.root outputFile=file:/tmp/almorton/step1_HZJ_bbbb_MS55_ctauS1.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_bbbb_MS55_ctauS10.root outputFile=file:/tmp/almorton/step1_HZJ_bbbb_MS55_ctauS10.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_bbbb_MS55_ctauS100.root outputFile=file:/tmp/almorton/step1_HZJ_bbbb_MS55_ctauS100.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_bbbb_MS55_ctauS1000.root outputFile=file:/tmp/almorton/step1_HZJ_bbbb_MS55_ctauS1000.root

cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_bbbb_MS40_ctauS1.root outputFile=file:/tmp/almorton/step1_HZJ_bbbb_MS40_ctauS1.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_bbbb_MS40_ctauS10.root outputFile=file:/tmp/almorton/step1_HZJ_bbbb_MS40_ctauS10.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_bbbb_MS40_ctauS100.root outputFile=file:/tmp/almorton/step1_HZJ_bbbb_MS40_ctauS100.root
cmsRun step1_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_2017.py inputFiles=file:/tmp/almorton/GEN-SIM_HZJ_bbbb_MS40_ctauS1000.root outputFile=file:/tmp/almorton/step1_HZJ_bbbb_MS40_ctauS1000.root
